name: Run Comprehensive AI Analysis
on:
  schedule:
    - cron: '*/5 * * * *' # هر 4 ساعت
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install feedparser pandas yfinance
      - run: python main.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update AI analysis and dashboard"
          file_pattern: "sentiment.txt strategy_data.json dashboard.html"
